all:
	g++ -o my_program main.cpp `sdl2-config --cflags --libs`
image:
	g++ -o my_program main.cpp `sdl2-config --cflags --libs` -lSDL2_image
keyboard:
	g++ -o my_program keyBoardEvent.cpp `sdl2-config --cflags --libs`
